### ISSUE TITLE
update make_instcat to include dithering

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/imsim_deep_pipeline#1]

**Comment by danielsf** [comment]
I think this branch

https://github.com/LSSTDESC/imsim_deep_pipeline/tree/include_dithering

will work.  It looks like the code in this repo is designed to be run on a very specific system.  Am I able to log onto it for testing purposes, or are you handling that, @jchiang87.

Also, do you have Lynne's dithered OpSim database from this thread

https://github.com/lsst/sims_operations/pull/55#issuecomment-272330385

?

**Comment by jchiang87** [comment]
Thanks, @danielsf!   If you have a SLAC account, you can log in to a slac rhel6 machine, and run and test it, but I will be testing it anyways when I exercise it with the rest of the pipeline, so there isn't a need for you to do so separately.   Please go ahead and make the pull-request, and if I run into any issues while trying it out, I'll post the comments there.

**Comment by jchiang87** [comment]
closed by #2

**Comment by danielsf** [comment]
I forgot to mention: you will need to run with this branch of sims_catUtils

https://github.com/lsst/sims_catUtils/tree/feature/SIM-2249/include_dither

The branch is under review.  I will issue a new lsst_sims release when it gets merged.
